spring:
  application:
    name: yum_api_gateway_server
  cloud:
    gateway:
      routes:
        - id: yum-ingredient-server
          uri: http://${INGREDIENT_SERVER_NAME}:${INGREDIENT_SERVER_PORT}
          predicates:
            - Path=/api/ingredients/**