spring:
  application:
    name: yum_api_gateway_server
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      routes:
        - id: yum-ingredient-server
          uri: http://localhost:${INGREDIENT_SERVER_PORT}
          predicates:
            - Path=/api/ingredients/**