server:
  max-http-request-header-size: 65536

spring:
  application:
    name: yum_api_gateway_server
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      routes:
        - id: yum-ingredient-server
          uri: http://${INGREDIENT_SERVER_NAME}:${INGREDIENT_SERVER_PORT}
          predicates:
            - Path=/api/ingredients/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    use-root-path: true
    urls:
      - name: Ingredient Service API
        url: http://localhost:8080/api/ingredients/v3/api-docs